export const API = 'API'
export const API_REQUEST = 'API_REQUEST'
export const API_SUCCESS = 'API_SUCCESS'
export const API_ERROR = 'API_ERROR'

export const LOGIN_S = 'LOGIN_SUCCESS'
export const LOGIN_F = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

export const FETCH_META_S = 'FETCH_META_S'
export const FETCH_META_F = 'FETCH_META_F'

export const CAUSE_S = 'CAUSE_SUCCESS'
export const CAUSE_F = 'CAUSE_FAIL'


export const CATEGORY_S = 'CATEGORY_S'
export const CATEGORY_F = 'CATEGORY_F'

export const ADD_CHARITY_DETAILS_STEPS_1 = 'ADD_CHARITY_DETAILS_STEPS_1'
export const ADD_CHARITY_DETAILS_STEPS_2 = 'ADD_CHARITY_DETAILS_STEPS_2'
export const ADD_CHARITY_DETAILS_STEPS_3 = 'ADD_CHARITY_DETAILS_STEPS_3'
export const ADD_CHARITY_DETAILS_STEPS_4 = 'ADD_CHARITY_DETAILS_STEPS_4'

export const CHARITY_LISTING_S = 'CHARITY_LISTING_S'
export const CHARITY_LISTING_F = 'CHARITY_LISTING_F'

export const CHARITY_DETAIL_S = 'CHARITY_DETAIL_S'
export const CHARITY_DETAIL_F = 'CHARITY_DETAIL_F'

export const CHARITY_VERIFICTAION_S = 'CHARITY_VERIFICTAION_S'
export const CHARITY_VERIFICTAION_F = 'CHARITY_VERIFICTAION_F'


// admin cause 
export const CAUSE_LISTING_SUCCESS = 'CAUSE_LISTING_SUCCESS'
export const CAUSE_LISTING_FAIL = 'CAUSE_LISTING_FAIL'

export const CAUSE_ADD_SUCCESS = 'CAUSE_ADD_SUCCESS'
export const CAUSE_ADD_FAIL = 'CAUSE_ADD_FAIL'

export const CAUSE_DETAIL_SUCCESS = 'CAUSE_DETAIL_SUCCESS'
export const CAUSE_DETAIL_FAIL = 'CAUSE_DETAIL_FAIL'

export const CAUSE_DELETE_SUCCESS = 'CAUSE_DELETE_SUCCESS'
export const CAUSE_DELETE_FAIL = 'CAUSE_DELETE_FAIL'

export const CAUSE_EDIT_SUCCESS = 'CAUSE_EDIT_SUCCESS'
export const CAUSE_EDIT_FAIL = 'CAUSE_EDIT_FAIL'

export const CAUSE_ACTIVEINACTIVE_SUCCESS = 'CAUSE_ACTIVEINACTIVE_SUCCESS'
export const CAUSE_ACTIVEINACTIVE_FAIL = 'CAUSE_ACTIVEINACTIVE_FAIL'

// -------------------------------

// New charity Accept

export const CHARITY_LISTING_ACCEPT_SUCCESS = 'CHARITY_LISTING_ACCEPT_SUCCESS'
export const CHARITY_LISTING_ACCEPT_FAIL = 'CHARITY_LISTING_ACCEPT_FAIL'


// ---------------------------------

//  Charity Management

export const CHARITY_MANAGE_ADD_SUCCESS = 'CHARITY_MANAGE_ADD_SUCCESS'
export const CHARITY_MANAGE_ADD_FAIL = 'CHARITY_MANAGE_ADD_FAIL'

export const CHARITY_MANAGE_DETAIL_SUCCESS = 'CHARITY_MANAGE_DETAIL_SUCCESS'
export const CHARITY_MANAGE_DETAIL_FAIL = 'CHARITY_MANAGE_DETAIL_FAIL'

export const CHARITY_MANAGE_DELETE_SUCCESS = 'CHARITY_MANAGE_DELETE_SUCCESS'
export const CHARITY_MANAGE_DELETE_FAIL = 'CHARITY_MANAGE_DELETE_FAIL'

export const CHARITY_MANAGE_EDIT_SUCCESS = 'CHARITY_MANAGE_EDIT_SUCCESS'
export const CHARITY_MANAGE_EDIT_FAIL = 'CHARITY_MANAGE_EDIT_FAIL'

export const CHARITY_MANAGE_UPDATE_SUCCESS = 'CHARITY_MANAGE_UPDATE_SUCCESS'
export const CHARITY_MANAGE_UPDATE_FAIL = 'CHARITY_MANAGE_UPDATE_FAIL'

export const CHARITY_MANAGE_ACTIVEINACTIVE_SUCCESS = 'CHARITY_MANAGE_ACTIVEINACTIVE_SUCCESS'
export const CHARITY_MANAGE_ACTIVEINACTIVE_FAIL = 'CHARITY_MANAGE_ACTIVEINACTIVE_FAIL'

// -------------------------------

// Charity Category

export const CHARITY_CATEGORY_LISTING_SUCCESS = 'CHARITY_CATEGORY_LISTING_SUCCESS'
export const CHARITY_CATEGORY_LISTING_FAIL = 'CHARITY_CATEGORY_LISTING_FAIL'

export const CHARITY_CATEGORY_ADD_SUCCESS = 'CHARITY_CATEGORY_ADD_SUCCESS'
export const CHARITY_CATEGORY_ADD_FAIL = 'CHARITY_CATEGORY_ADD_FAIL'

export const CHARITY_CATEGORY_DETAIL_SUCCESS = 'CHARITY_CATEGORY_DETAIL_SUCCESS'
export const CHARITY_CATEGORY_DETAIL_FAIL = 'CHARITY_CATEGORY_DETAIL_FAIL'

export const CHARITY_CATEGORY_DELETE_SUCCESS = 'CHARITY_CATEGORY_DELETE_SUCCESS'
export const CHARITY_CATEGORY_DELETE_FAIL = 'CHARITY_CATEGORY_DELETE_FAIL'

export const CHARITY_CATEGORY_EDIT_SUCCESS = 'CHARITY_CATEGORY_EDIT_SUCCESS'
export const CHARITY_CATEGORY_EDIT_FAIL = 'CHARITY_CATEGORY_EDIT_FAIL'

export const CHARITY_CATEGORY_UPDATE_SUCCESS = 'CHARITY_CATEGORY_UPDATE_SUCCESS'
export const CHARITY_CATEGORY_UPDATE_FAIL = 'CHARITY_CATEGORY_UPDATE_FAIL'

export const CHARITY_CATEGORY_ACTIVEINACTIVE_SUCCESS = 'CHARITY_CATEGORY_ACTIVEINACTIVE_SUCCESS'
export const CHARITY_CATEGORY_ACTIVEINACTIVE_FAIL = 'CHARITY_CATEGORY_ACTIVEINACTIVE_FAIL'

// -------------------------------


export const CAUSE_EDIT_S = 'CAUSE_EDIT_S'
export const CAUSE_EDIT_F = 'CAUSE_EDIT_F'


export const HOMEPAGE_UPDATE_S = 'HOMEPAGE_UPDATE_S'
export const HOMEPAGE_UPDATE_F = 'HOMEPAGE_UPDATE_F'

export const HOMEPAGE_DETAIL_S = 'HOMEPAGE_DETAIL_S'
export const HOMEPAGE_DETAIL_F = 'HOMEPAGE_DETAIL_F'

export const CAUSE_UPDATE_S = 'CAUSE_UPDATE_S'
export const CAUSE_UPDATE_F = 'CAUSE_UPDATE_F'

export const COUNTRY_S = 'COUNTRY_S'
export const COUNTRY_F = 'COUNTRY_F'

export const STATE_S = 'STATE_S'
export const STATE_F = 'STATE_F'

export const CITY_S = 'CITY_S'
export const CITY_F = 'CITY_F'